version: '2'
services:
    web:
        image: js
        ports:
            - "80:8080"
        volumes_from:
            - container:js_data
            - container:dotfiles
        command: bash -c "npm run serve"
